### ISSUE TITLE
SME Review Checklist

### ISSUE THREAD

**Issue by justineechen** [justineechen/test-issues#10]
SME Review
 
 - [ ] Ensure technical accuracy for code
 - [ ] Ensure technical accuracy for guide
 - [ ] Ensure technical accuracy for overall content
