### ISSUE TITLE
Peer Review/Testing Checklist

### ISSUE THREAD

**Issue by justineechen** [justineechen/test-issues#12]
Peer Review
 
 - [ ] Working instruction and sample code
 - [ ] Quality of code (best coding practices)
 - [ ] Quality and presentation of guide according to [Structure and Style Guideline](https://github.com/OpenLiberty/draft-guides-template/wiki/Guidelines-for-Structure-and-Styles)
 - [ ] Consistency of guide with template and other guides
 - [ ] Examples with the right outcomes are provided
 - [ ] Example with the wrong outcomes, if any, are provided
 - [ ] Check that all licensing statements are properly stated in all files
 - [ ] Check that the pom.xml, server.xml, etc files are clean up
 - [ ] Check that the directories are properly structured
 - [ ] Test the guide on 3 platforms: Mac, Win, Liniux
 - [ ] If any URL visits, try them on different browsers: Firefox, Chrome, Safari
 - [ ] If any URL visits, try curl command where applicable 
 - [ ] Ensure that the guide is using the latest version of the liberty-maven-plugin or gradle plugin
 - [ ] Check that some of these `page-tags` are used in a guide: `MicroProfile, Maven, Docker, Kubernetes, Gradle, Java EE, Security`. Only these tags are visible on the website. Latest list [here](https://github.com/OpenLiberty/openliberty.io/blob/master/src/main/content/_includes/visible-tags.liquid). 
 - [ ] Check that other tags relevant to the guide are added. These will not be visible on the website, but can help the guide to be searchable. 
 - [ ] Check the `attribution` statement is accurate for the guide. 
 
 Peer Testing
 
 Guide’s contributor’s (if available, otherwise peer tester’s) responsibility: 
 - [ ] Define test coverage and review with team (including guide contributor, if available)
 - [ ] Define detail test cases
 - [ ] Consider corner cases targeting the specific guide
 - [ ] Consider different platform tests, ie, Mac, Windows, Linux – New!
 - [ ] Consider corner cases UI tests
 - [ ] Consider testing URL on all browsers, ie, FF, Chrome, Safari - New!
 - [ ] Consider testing the `curl` command for URL visits
 - [ ] Consider Consider building with both Maven and Gradel build tools
 - [ ] Testing with different IDEs, ie, Atom, VS.code, Eclipse, IntelliJ, (Microclimate) - New!
 - [ ] Run Acrolink Checker on draft (above 70 score approximately)
 - [ ] Consider SEO title and description for the guides
 - [ ] Ensure automated test is enable, setup with Travis CI, and schedule tests
  - [ ] Run `diff -r start/ finish/`
 - [ ] Ensure that the automation tests are able to run with continuous daily build
 
 Peer Tester’s responsibility:
  - [ ] Check the appearance of the guide on test site for the following items:
  - Table of contents
  - Headings
 - Paragraphs
 - code snippets
 - outputs
 - links
 - hotspots
 - [ ] Test the guide end-to-end with working instruction and sample code
 - [ ] Perform all the defined test cases

**Comment by justineechen** [comment]
<img width="704" alt="Screen Shot 2019-05-15 at 2 07 00 PM" src="https://user-images.githubusercontent.com/18709242/57798537-ef59b700-771a-11e9-80a5-8c391f90625d.png">
