### ISSUE TITLE
Publishing Tasks Checklist

### ISSUE THREAD

**Issue by justineechen** [justineechen/test-issues#5]
Publishing Tasks
 - [ ] Rename the guide repo
 - [ ] Request to refresh openliberty.io site
  - [ ] Add a tag by creating a new release for this repo with name "1st-release"
