### ISSUE TITLE
Pre-Publishing Tests Checklist

### ISSUE THREAD

**Issue by justineechen** [justineechen/test-issues#6]
Pre-Publishing Tests
 - [ ] Check appearance (contents, headings, paragraphs, code snippets, outputs, links, hotspots) of the guide on test site, ie, qa-guides
 - [ ] Read through the guide
 - [ ] Clone repo and test finish directory with no error
 - [ ] Run `diff -r start/ finish/`
 - [ ] Follow the instruction in the guide to test that it is working
 - Use the `copy` buttons instead of typing
 - [ ] Check that the release date on the readme.adoc is the publishing date
