### ISSUE TITLE
Post-Publishing Tests Checklist

### ISSUE THREAD

**Issue by justineechen** [justineechen/test-issues#7]
Post-Publishing Tests
 - [ ] Check appearance (contents, headings, paragraphs, code snippets, outputs, links) of the guide on openliberty.io
 - [ ] Clone repo and test finish directory with no error
 
 Other post-publishing tasks (to be done by the Admin Team)
 - [ ] Add description for the repo with link to the guides published website
 - [ ] Ensure automated test using Travis, see [instruction](https://github.ibm.com/was-liberty/openliberty-guides-team/wiki/Automation-Tests-For-OpenLiberty-Guides#setup-travis-ci-tests-for-openliberty-guides)
 - [ ] Enable pull creation notification on the repo for `was-lib-guides-alerts`, see [instruction](https://github.ibm.com/was-liberty/openliberty-guides-team/wiki/Automation-Tests-For-OpenLiberty-Guides#subscribing-static-guides-repositories-to-a-slack-channel)
 - [ ] Add the new guides repo to the `OpenLiberty/guides-common` ZenHub board
 - [ ] (Optional) Send announcement to slack channel(s)
 - [ ] Consider SEO title and description for the guides
 - [ ] Enable `master` branch lock down
